services:
  airflow:
    build: .        # 현재 디렉터리의 Dockerfile을 사용
    env_file:
      - .env       # .env에서 KAKAO_REST_API_KEY를 로드
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      SCHOOL_DATA_CSV: /opt/airflow/mlops/middle_schools.csv
    ports:
      - '8080:8080'  # Host 8080 ↔ Container 8080
    volumes:
      - ./mlops:/opt/airflow/mlops   # 코드 라이브 마운트
      - ./airflow/dags/mlops_project:/opt/airflow/dags
    restart: unless-stopped
